In [1]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[45:55]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
45                4.8               3.0                1.4               0.3   
46                5.1               3.8                1.6               0.2   
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

        flower  
45      setosa  
46      setosa  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor  
52  versicolor  
53  versicolor  
54  versicolor

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.30)

In [6]:
from sklearn.svm import SVC
model = SVC(kernel = 'rbf', C = 30, gamma = 'auto')
model.fit(X_train, y_train)
model.score(X_test, y_test)

1.0

In [8]:
# K_Fold to check the score of SVC with different parameters like kernel, C and gamma

from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel = 'rbf', C = 30, gamma = 'auto'), iris.data, iris.target)

array([0.96666667, 1.        , 0.9       , 0.93333333, 1.        ])

In [9]:
cross_val_score(SVC(kernel = 'linear', C = 30, gamma = 'auto'), iris.data, iris.target)

array([1. , 1. , 0.9, 0.9, 1. ])

In [10]:
cross_val_score(SVC(kernel = 'rbf', C = 20, gamma = 'auto'), iris.data, iris.target)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [11]:
import numpy as np
kernel = ['rbf', 'linear']
C = [1, 10, 20]
avg_score = {}
for kval in kernel:
    for cval in C:
        cv_scores = cross_val_score(SVC(kernel=kval, C=cval, gamma='auto'), iris.data, iris.target, cv = 5)
        avg_score[kval + '_' + str(cval)] = np.average(cv_scores)

avg_score

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [12]:
# the above for loop thing with GridSearchCV

from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(SVC(gamma = 'auto'), {
    'C' : [1, 10, 20, 30],
    'kernel' : ['rbf', 'linear']
}, cv=5, return_train_score=False)

clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00139666, 0.00079689, 0.00159612, 0.00312657, 0.00100012,
        0.00099697, 0.00101962, 0.        ]),
 'std_fit_time': array([4.88033595e-04, 3.98447555e-04, 4.88734724e-04, 4.15778143e-03,
        6.30921900e-04, 2.02079965e-06, 3.96534180e-05, 0.00000000e+00]),
 'mean_score_time': array([0.00079732, 0.00099745, 0.00099673, 0.00059862, 0.00079908,
        0.00079803, 0.00059729, 0.        ]),
 'std_score_time': array([3.98659802e-04, 6.30826593e-04, 9.72560790e-07, 7.98320856e-04,
        3.99555669e-04, 7.46175552e-04, 4.87683333e-04, 0.00000000e+00]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_valu

In [13]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001397      0.000488         0.000797    3.986598e-04       1   
1       0.000797      0.000398         0.000997    6.308266e-04       1   
2       0.001596      0.000489         0.000997    9.725608e-07      10   
3       0.003127      0.004158         0.000599    7.983209e-04      10   
4       0.001000      0.000631         0.000799    3.995557e-04      20   
5       0.000997      0.000002         0.000798    7.461756e-04      20   
6       0.001020      0.000040         0.000597    4.876833e-04      30   
7       0.000000      0.000000         0.000000    0.000000e+00      30   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
6          rbf     {'C': 30, 'kernel': 'rbf'}           0.966667   
7       linear  {'C': 30, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   
6                1.0           0.900000           0.933333                1.0   
7                1.0           0.900000           0.900000                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6  
6         0.960000        0.038873                7  
7         0.960000        0.048990                7

In [14]:
df[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667
6      30          rbf         0.960000
7      30       linear         0.960000

In [15]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_

In [16]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [17]:
clf.best_score_

0.9800000000000001

In [21]:
# The GridSearchCV can require more computation power for large datasets
# So to tackle this we have RandomizedSearchCV that randomly takes the parameter and run the model for specified iterations

from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(gamma = 'auto'), {
    'C' : [1, 10, 20, 30],
    'kernel' : ['rbf', 'linear']
},  cv = 5,
    return_train_score=False,
    n_iter=3)

rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1      10       linear         0.973333
2      30          rbf         0.960000

In [22]:
rs.best_score_

0.9800000000000001