In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
X = df.drop('Outcome', axis = 'columns')
y = df.Outcome

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled[:3]

array([[ 0.63994726,  0.84832379,  0.14964075,  0.90726993, -0.69289057,
         0.20401277,  0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575,  0.53090156, -0.69289057,
        -0.68442195, -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, -1.28821221, -0.69289057,
        -1.10325546,  0.60439732, -0.10558415]])

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=10, stratify=y)

In [15]:
X_train.shape

(576, 8)

In [16]:
X_test.shape

(192, 8)

In [17]:
y_train.value_counts()

0    375
1    201
Name: Outcome, dtype: int64

In [18]:
201/375

0.536

In [19]:
y_test.value_counts()

0    125
1     67
Name: Outcome, dtype: int64

In [20]:
67/125

0.536

Train using Stand alone Model

In [24]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

scores = cross_val_score(DecisionTreeClassifier(), X_scaled, y, cv = 5)
scores

array([0.67532468, 0.68831169, 0.68831169, 0.77777778, 0.71895425])

In [25]:
scores.mean()

0.7097360156183685

In [30]:
from sklearn.ensemble import BaggingClassifier

baggingClassifier = BaggingClassifier(
    base_estimator = DecisionTreeClassifier(),
    n_estimators = 100,
    max_samples = 0.8,
    oob_score = True,
    random_state=0
)

baggingClassifier.fit(X_train, y_train)
baggingClassifier.oob_score_

0.7534722222222222

In [31]:
baggingClassifier.score(X_test, y_test)

0.7760416666666666

In [34]:
baggingClassifier = BaggingClassifier(
    base_estimator = DecisionTreeClassifier(),
    n_estimators = 100,
    max_samples = 0.8,
    oob_score = True,
    random_state=0
)

scores = cross_val_score(baggingClassifier, X, y, cv = 5)
scores.mean()

0.7578728461081402

In [35]:
from sklearn.ensemble import RandomForestClassifier

clf = cross_val_score(RandomForestClassifier(), X, y, cv = 5)
clf

array([0.75324675, 0.73376623, 0.74675325, 0.81699346, 0.75163399])

In [36]:
clf.mean()

0.7604787369493252

In [37]:
baggingClassifier = BaggingClassifier(
    base_estimator = RandomForestClassifier(),
    n_estimators = 100,
    max_samples = 0.8,
    oob_score = True,
    random_state=0
)

scores = cross_val_score(baggingClassifier, X, y, cv = 5)
scores.mean()

0.7643918173329938